export const blogs = [
    {
        slug: "lessons-from-property-brothers-1",
        title: "Lessons from the Property Brothers",
        img: "blogEjemplo",
        alt: "Property Brothers Blog Post",
        author: "Jack Daniels",
        authorImg: "author",
        date: "February 21, 2018",
        summary: "Each product requires individual approach. Partnering up with small and big companies, we struggle for success of their products together. Staying connected with our clients helps us reach the goal and implement ideas.",
    },
    {
        slug: "2",
        title: "Lessons from the Property Brothers",
        img: "blogEjemplo",
        alt: "",
        author: "Jack Daniels",
        authorImg: "author",
        date: "February 21, 2018",
        summary: "Each product requires individual approach. Partnering up with small and big companies, we struggle for success of their products together. Staying connected with our clients helps us reach the goal and implement ideas.",
    },
    {
        slug: "3",
        title: "Lessons from the Property Brothers",
        img: "blogEjemplo",
        alt: "",
        author: "Jack Daniels",
        authorImg: "author",
        date: "February 21, 2018",
        summary: "Each product requires individual approach. Partnering up with small and big companies, we struggle for success of their products together. Staying connected with our clients helps us reach the goal and implement ideas.",
    },
    {
        slug: "4",
        title: "Lessons from the Property Brothers",
        img: "blogEjemplo",
        alt: "",
        author: "Jack Daniels",
        authorImg: "author",
        date: "February 21, 2018",
        summary: "Each product requires individual approach. Partnering up with small and big companies, we struggle for success of their products together. Staying connected with our clients helps us reach the goal and implement ideas.",
    },
    {
        slug: "5",
        title: "Lessons from the Property Brothers",
        img: "blogEjemplo",
        alt: "",
        author: "Jack Daniels",
        authorImg: "author",
        date: "February 21, 2018",
        summary: "Each product requires individual approach. Partnering up with small and big companies, we struggle for success of their products together. Staying connected with our clients helps us reach the goal and implement ideas.",
    },
];