export const projects = [
  {
    slug: "corro-con-jonas",
    title: "Corro con Jonás",
    description: "Una carrera, un corredor y un mensaje oculto.",
    brand: "logo-fuca",
    altBrand: "Logo Fuca",
    img: "home_corro_con_jonas",
    altImg: "Campaña Corro con Jonas",
    subtitle: "Una carrera, un corredor y un mensaje oculto. #CorroConJonás es una campaña de FUCA, ganadora del premio Obrar 2015.",
    objective: 'La Fundación FUCA se enfrenta cada año al desafío de llevar su mensaje de prevención y concientización sobre el cáncer a más personas. El problema radica en que muchas veces el cáncer es "invisible" a simple vista, pero detectarlo a tiempo puede salvar vidas. La tarea encomendada fue clara: aumentar la visibilidad y el impacto de su mensaje de detección temprana del cáncer.',
    campain: ['Para esta campaña, convocamos a Jonás Gutiérrez, talentoso jugador de fútbol argentino y ex miembro de la selección nacional, quien enfrentó y superó un cáncer testicular años atrás. Junto a FUCA, invitamos a Jonás a correr la maratón Bs. As. 42K en 2014 y lanzamos el hashtag #CorroConJonas para que las personas pudieran enviar sus mensajes de aliento a través de Twitter (hoy “X”).', 'Equipamos a Jonás con unos auriculares conectados a una computadora que convertía cada tweet en audio, permitiéndole escuchar los mensajes en tiempo real mientras corría, logrando así que todos pudieran “correr con Jonás”. Además, creamos una camiseta especial que, al contacto con el sudor, revelaba un mensaje oculto, simbolizando cómo el cáncer puede ser invisible pero detectable.'],
    results: {
      texts: ['La campaña fue un rotundo éxito, alcanzando más de 6 millones de impresiones en Twitter y logrando una cobertura masiva en medios de comunicación, desde portales deportivos hasta los principales canales de noticias, incluyendo diarios internacionales como los de España e Inglaterra. Esto permitió no solo alcanzar un impacto internacional, sino también llevar el mensaje de FUCA a un público amplio y diverso.', 'Lo más importante es que conseguimos transmitir el mensaje de prevención y detección temprana del cáncer de manera efectiva y emocional.'],
      videos: ["", ""],
    },
    awards: {
      texts: ["Si bien, Jonás no ganó la maratón, se ganó el orgullo y respeto de todo un país.", "Y por nuestra parte, nos enorgullece destacar que la campaña ganó la máxima distinción en los Premios Obrar del Consejo Publicitario Argentino.", "PREMIO OBRAR - 6° Edición (2015) - Categoría: PyMES.", "Así como también un reconocimiento a nivel iberoamericano, tras quedar como finalistas del Caracol de Plata."],
      press: [
        {
          name: "Adlatina",
          link: "https://www.adlatina.com/articulo.php?slug=/publicidad/el-consejo-publicitario-argentino-revel%C3%B3-los-ganadores-de-los-premios-obrar",
        },
        {
          name: "Dossiernet",
          link: "https://dossiernet.com/articulo/el-consejo-publicitario-argentino-entrego-los-premios-obrar-2015/5749",
        },
        {
          name: "Radio Mitre",
          link: "https://radiomitre.cienradios.com/archivo/se-conocieron-los-ganadores-de-los-premios-obrar/",
        },
      ],
    },
    feature: true,
  },
  {
    slug: "fabrica-de-confianza",
    title: "Fábrica de Confianza",
    description: 'Video institucional: "Mi papá trabaja en una fábrica de confianza".',
    brand: "logo-sika",
    altBrand: "Logo Sika",
    img: "home_sika_fabrica_de_confianza",
    altImg: "Campaña Fábrica de Confianza",
    subtitle: 'Sika lanza su nuevo video institucional con una tierna historia: "Mi papá trabaja en una fábrica de confianza".',
    objective: "Sika, líder en productos y soluciones para la construcción en Argentina, quería celebrar sus años de trayectoria en el país con un nuevo video institucional. El problema a resolver era representar no solo la calidad, innovación y desarrollo de la marca, sino también reflejar su lado más humano. La tarea encomendada fue clara: crear una pieza que destacara la esencia humana de Sika, alejándose de los clichés típicos de los videos corporativos.",
    campain: ['Para esta campaña, decidimos tomar un enfoque innovador y emocional. En lugar de seguir la estructura tradicional de los videos institucionales, desarrollamos un spot que contara la historia de Sika desde la perspectiva inocente de una niña que admira a su papá, quien trabaja en Sika, o como ella la llama: "una fábrica de confianza".', "El video narra las cualidades de la empresa a través de los ojos de esta niña, creando una conexión emocional con el espectador y destacando la confianza y el compromiso humano detrás de la marca. Este enfoque no solo capturó la esencia de Sika, sino que también presentó una historia tierna y memorable."],
    results: {
      texts: ["El video institucional fue un gran éxito, logrando una fuerte conexión emocional con el público y destacando en el sector por su enfoque innovador. La campaña no solo reforzó la imagen de Sika como líder en calidad e innovación, sino que también humanizó la marca, mostrando su compromiso con las personas detrás de los productos."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "descubre-una-vida-mas-qualy",
    title: "Descubre una vida + Qualy",
    description: "Qualy te sorprende con este impresionante flashmob.",
    brand: "logo-qualy",
    altBrand: "Logo Qualy",
    img: "home_descubre_una_vida_mas_qualy",
    altImg: "Campaña Descubre una vida + Qualy",
    subtitle: "Equilibrio, sabor y vitalidad. Qualy te sorprende todos los días, y ahora más gracias a este impresionante flashmob.",
    objective: "Qualy es una famosa marca de origen brasileño, especializada en la fabricación de diferentes tipos de margarinas con más de 80 años de trayectoria. Sin embargo, en el mercado chileno no había logrado la misma relevancia. El cliente nos pidió desarrollar una campaña de activaciones para promocionar la marca en Chile, generar mayor pregnancia y comunicar sus beneficios de manera efectiva.",
    campain: ["Qualy es una excelente alternativa tanto para cocinar como para el desayuno o la merienda, promoviendo una alimentación más equilibrada. Con esto en mente, decidimos invitar a la gente a cortar su rutina diaria, tomar una merecida pausa y animarse a descubrir una vida más equilibrada: una vida + Qualy.", "Desarrollamos una activación en el centro de Santiago de Chile, donde instalamos una silla junto a un cartel invitando a la gente a sentarse. Cada vez que una persona se sentaba, sonaba una bocina dando inicio a un espectacular flashmob inspirado en el equilibrio, la liviandad y la vitalidad. Esta intervención capturó la atención del público y transmitió los valores de la marca de manera lúdica y memorable."],
    results: {
      texts: ["Miles de personas presenciaron las múltiples activaciones del flashmob, logrando el objetivo de dar a conocer la marca, mejorar su pregnancia y reconocimiento. Además, aprovechamos la activación para entregar cientos de folletos, invitando a la gente a seguir a Qualy en redes sociales y alcanzando nuevos seguidores en pocas horas."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "paty-posicionamiento-regional",
    title: "Paty, posicionamiento regional",
    description: 'Un viaje por el tiempo para descubrir el poder de "LA LEYENDA".',
    brand: "logo-paty",
    altBrand: "Logo Paty",
    img: "home_posicionamiento_regional",
    altImg: "Campaña Paty, posicionamiento regional",
    subtitle: 'Paty, junto al famoso comediante chileno Rodrigo Salinas, te invita a un viaje por el tiempo para descubrir el poder de "LA LEYENDA".',
    objective: "Paty, una marca líder en Argentina, enfrentaba el desafío de lograr un reconocimiento similar en el mercado chileno. En 2016, la empresa decidió lanzar una campaña 360° para incrementar la pregnancia y el engagement de la marca en Chile, abordando así el problema de su baja visibilidad y posicionamiento en este mercado.",
    campain: ["Para alcanzar este nuevo posicionamiento en Chile, lanzamos una campaña protagonizada por el comediante y actor Rodrigo Salinas, una figura reconocida en el país. Su participación dio a Paty una comunicación fresca y divertida, manteniendo su espíritu de TRADICIÓN EN CARNES.", 'La campaña incluyó diferentes activaciones: Un gran evento en las playas de Viña del Mar, Reñaca y La Serena, donde los usuarios podían subirse a un toro mecánico con la forma del logo de Paty; y una serie de videos interactivos en los que las personas podían actuar y aparecer junto al comediante en un "viaje a través del tiempo".', "El lema de la campaña, ¡Anímate a domar tu hambre! #SubetealaLeyenda, invitaba al público a participar activamente y a conocer más sobre la marca."],
    results: {
      texts: ["La activación de Paty en la playa atrajo a más de 6.600 personas, y más de 4.900 recibieron su video subiéndose al toro e intentando DOMAR A LA LEYENDA. Estos videos fueron ampliamente compartidos en redes sociales, superando los 760.000 puntos de contacto potenciales.", "La campaña logró aumentar significativamente el nivel de awareness dentro del mercado chileno, alcanzando un récord de engagement en redes sociales y triplicando las ventas respecto al mismo período del año anterior."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "psicologo-del-color",
    title: "Psicólogo del color",
    description: "Sodimac convierte a uno de sus asesores en un psicólogo para ayudar a sus clientes a elegir el mejor color.",
    brand: "logo-sodimac",
    altBrand: "Logo Sodimac",
    img: "home_psicologo_del_color",
    altImg: "Campaña Psicólogo del color",
    subtitle: "En esta campaña, Sodimac convierte a uno de sus asesores en un psicólogo para ayudar a sus clientes a elegir el mejor color.",
    objective: "Sodimac cuenta con un sector especializado para pinturas, donde los clientes pueden recibir asesoramiento personalizado y un servicio de entintado completamente gratis. Sin embargo, el desafío era comunicar este servicio y resaltar los beneficios de contar con asesores especializados, para incrementar el conocimiento y uso del servicio. El objetivo planteado era claro: lanzar una campaña en redes sociales para destacar estos beneficios y atraer más clientes a los servicios de pintura de Sodimac.",
    campain: ["La psicología del color es una rama de la psicología que estudia cómo los colores influyen en el comportamiento y las emociones de las personas. Basándonos en esta premisa, desarrollamos una campaña que convertía a uno de los asesores de Sodimac en un psicólogo especializado en colores.", 'Decidimos lanzar una serie de videos humorísticos en los que este "psicólogo del color" ayudaba a los clientes a elegir el color perfecto para sus hogares, demostrando así el valor de la asesoría personalizada. La campaña buscaba comunicar este servicio de una forma original y relajada, utilizando insights con los que el público se pudiera identificar fácilmente.'],
    results: {
      texts: ["La campaña fue recibida con gran entusiasmo por los usuarios, generando un amplio alcance en redes sociales y aumentando significativamente el número de consultas al sector de pinturas en las diferentes tiendas Sodimac del país. Esta estrategia no solo incrementó la visibilidad del servicio, sino que también fortaleció la percepción de la marca como experta en soluciones de pintura personalizadas."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "man-in-black",
    title: "Man in Black",
    description: "HTML, Development",
    brand: "logo-brand3",
    altBrand: "Image",
    img: "works06",
    altImg: "Image",
    subtitle: "",
    objective: "",
    campain: ["", ""],
    results: {
      texts: ["", ""],
      videos: ["", ""],
    },
    awards: {
      texts: ["", ""],
      press: [
        {
          name: "",
          link: "",
        },
        {
          name: "",
          link: "",
        },
      ],
    },
    feature: true,
  },
  {
    slug: "old-school",
    title: "Old School",
    description: "App Design, Development",
    brand: "logo-brand",
    altBrand: "Image",
    img: "works07",
    altImg: "Image",
    subtitle: "",
    objective: "",
    campain: ["", ""],
    results: {
      texts: ["", ""],
      videos: ["", ""],
    },
    awards: {
      texts: ["", ""],
      press: [
        {
          name: "",
          link: "",
        },
        {
          name: "",
          link: "",
        },
      ],
    },
    feature: true,
  },
  {
    slug: "paper-girl",
    title: "Paper Girl",
    description: "UI-UX Design, HTML, Development",
    brand: "logo-brand2",
    altBrand: "Image",
    img: "works08",
    altImg: "Image",
    subtitle: "",
    objective: "",
    campain: ["", ""],
    results: {
      texts: ["", ""],
      videos: ["", ""],
    },
    awards: {
      texts: ["", ""],
      press: [
        {
          name: "",
          link: "",
        },
        {
          name: "",
          link: "",
        },
      ],
    },
    feature: true,
  },
  {
    slug: "moto-wheel",
    title: "Moto Wheel",
    description: "Branding, Print Design",
    brand: "logo-brand3",
    altBrand: "Image",
    img: "works09",
    altImg: "Image",
    subtitle: "",
    objective: "",
    campain: ["", ""],
    results: {
      texts: ["", ""],
      videos: ["", ""],
    },
    awards: {
      texts: ["", ""],
      press: [
        {
          name: "",
          link: "",
        },
        {
          name: "",
          link: "",
        },
      ],
    },
    feature: true,
  },
  // NUEVOS
  {
    slug: "moto-wheel",
    title: "Moto Wheel",
    description: "Branding, Print Design",
    brand: "logo-brand3",
    altBrand: "Image",
    img: "works09",
    altImg: "Image",
    subtitle: "",
    objective: "",
    campain: ["", ""],
    results: {
      texts: ["", ""],
      videos: ["", ""],
    },
    awards: {
      texts: ["", ""],
      press: [
        {
          name: "",
          link: "",
        },
        {
          name: "",
          link: "",
        },
      ],
    },
  }
];
