export const projects = [
  {
    slug: "corro-con-jonas",
    title: "Corro con Jonás",
    description: "Una carrera, un corredor y un mensaje oculto.",
    brand: "logo-fuca",
    altBrand: "Logo Fuca",
    img: "home_corro_con_jonas",
    altImg: "Campaña Corro con Jonas",
    subtitle: "Una carrera, un corredor y un mensaje oculto. #CorroConJonás es una campaña de FUCA, ganadora del premio Obrar 2015.",
    objective: 'La Fundación FUCA se enfrenta cada año al desafío de llevar su mensaje de prevención y concientización sobre el cáncer a más personas. El problema radica en que muchas veces el cáncer es "invisible" a simple vista, pero detectarlo a tiempo puede salvar vidas. La tarea encomendada fue clara: aumentar la visibilidad y el impacto de su mensaje de detección temprana del cáncer.',
    campain: ['Para esta campaña, convocamos a Jonás Gutiérrez, talentoso jugador de fútbol argentino y ex miembro de la selección nacional, quien enfrentó y superó un cáncer testicular años atrás. Junto a FUCA, invitamos a Jonás a correr la maratón Bs. As. 42K en 2014 y lanzamos el hashtag #CorroConJonas para que las personas pudieran enviar sus mensajes de aliento a través de Twitter (hoy “X”).', 'Equipamos a Jonás con unos auriculares conectados a una computadora que convertía cada tweet en audio, permitiéndole escuchar los mensajes en tiempo real mientras corría, logrando así que todos pudieran “correr con Jonás”. Además, creamos una camiseta especial que, al contacto con el sudor, revelaba un mensaje oculto, simbolizando cómo el cáncer puede ser invisible pero detectable.'],
    results: {
      texts: ['La campaña fue un rotundo éxito, alcanzando más de 6 millones de impresiones en Twitter y logrando una cobertura masiva en medios de comunicación, desde portales deportivos hasta los principales canales de noticias, incluyendo diarios internacionales como los de España e Inglaterra. Esto permitió no solo alcanzar un impacto internacional, sino también llevar el mensaje de FUCA a un público amplio y diverso.', 'Lo más importante es que conseguimos transmitir el mensaje de prevención y detección temprana del cáncer de manera efectiva y emocional.'],
      videos: ["", ""],
    },
    awards: {
      texts: ["Si bien, Jonás no ganó la maratón, se ganó el orgullo y respeto de todo un país.", "Y por nuestra parte, nos enorgullece destacar que la campaña ganó la máxima distinción en los Premios Obrar del Consejo Publicitario Argentino.", "PREMIO OBRAR - 6° Edición (2015) - Categoría: PyMES.", "Así como también un reconocimiento a nivel iberoamericano, tras quedar como finalistas del Caracol de Plata."],
      press: [
        {
          name: "Adlatina",
          link: "https://www.adlatina.com/articulo.php?slug=/publicidad/el-consejo-publicitario-argentino-revel%C3%B3-los-ganadores-de-los-premios-obrar",
        },
        {
          name: "Dossiernet",
          link: "https://dossiernet.com/articulo/el-consejo-publicitario-argentino-entrego-los-premios-obrar-2015/5749",
        },
        {
          name: "Radio Mitre",
          link: "https://radiomitre.cienradios.com/archivo/se-conocieron-los-ganadores-de-los-premios-obrar/",
        },
      ],
    },
    feature: true,
  },
  {
    slug: "fabrica-de-confianza",
    title: "Fábrica de Confianza",
    description: 'Video institucional: "Mi papá trabaja en una fábrica de confianza".',
    brand: "logo-sika",
    altBrand: "Logo Sika",
    img: "home_sika_fabrica_de_confianza",
    altImg: "Campaña Fábrica de Confianza",
    subtitle: 'Sika lanza su nuevo video institucional con una tierna historia: "Mi papá trabaja en una fábrica de confianza".',
    objective: "Sika, líder en productos y soluciones para la construcción en Argentina, quería celebrar sus años de trayectoria en el país con un nuevo video institucional. El problema a resolver era representar no solo la calidad, innovación y desarrollo de la marca, sino también reflejar su lado más humano. La tarea encomendada fue clara: crear una pieza que destacara la esencia humana de Sika, alejándose de los clichés típicos de los videos corporativos.",
    campain: ['Para esta campaña, decidimos tomar un enfoque innovador y emocional. En lugar de seguir la estructura tradicional de los videos institucionales, desarrollamos un spot que contara la historia de Sika desde la perspectiva inocente de una niña que admira a su papá, quien trabaja en Sika, o como ella la llama: "una fábrica de confianza".', "El video narra las cualidades de la empresa a través de los ojos de esta niña, creando una conexión emocional con el espectador y destacando la confianza y el compromiso humano detrás de la marca. Este enfoque no solo capturó la esencia de Sika, sino que también presentó una historia tierna y memorable."],
    results: {
      texts: ["El video institucional fue un gran éxito, logrando una fuerte conexión emocional con el público y destacando en el sector por su enfoque innovador. La campaña no solo reforzó la imagen de Sika como líder en calidad e innovación, sino que también humanizó la marca, mostrando su compromiso con las personas detrás de los productos."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "descubre-una-vida-mas-qualy",
    title: "Descubre una vida + Qualy",
    description: "Qualy te sorprende con este impresionante flashmob.",
    brand: "logo-qualy",
    altBrand: "Logo Qualy",
    img: "home_descubre_una_vida_mas_qualy",
    altImg: "Campaña Descubre una vida + Qualy",
    subtitle: "Equilibrio, sabor y vitalidad. Qualy te sorprende todos los días, y ahora más gracias a este impresionante flashmob.",
    objective: "Qualy es una famosa marca de origen brasileño, especializada en la fabricación de diferentes tipos de margarinas con más de 80 años de trayectoria. Sin embargo, en el mercado chileno no había logrado la misma relevancia. El cliente nos pidió desarrollar una campaña de activaciones para promocionar la marca en Chile, generar mayor pregnancia y comunicar sus beneficios de manera efectiva.",
    campain: ["Qualy es una excelente alternativa tanto para cocinar como para el desayuno o la merienda, promoviendo una alimentación más equilibrada. Con esto en mente, decidimos invitar a la gente a cortar su rutina diaria, tomar una merecida pausa y animarse a descubrir una vida más equilibrada: una vida + Qualy.", "Desarrollamos una activación en el centro de Santiago de Chile, donde instalamos una silla junto a un cartel invitando a la gente a sentarse. Cada vez que una persona se sentaba, sonaba una bocina dando inicio a un espectacular flashmob inspirado en el equilibrio, la liviandad y la vitalidad. Esta intervención capturó la atención del público y transmitió los valores de la marca de manera lúdica y memorable."],
    results: {
      texts: ["Miles de personas presenciaron las múltiples activaciones del flashmob, logrando el objetivo de dar a conocer la marca, mejorar su pregnancia y reconocimiento. Además, aprovechamos la activación para entregar cientos de folletos, invitando a la gente a seguir a Qualy en redes sociales y alcanzando nuevos seguidores en pocas horas."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "paty-posicionamiento-regional",
    title: "Paty, posicionamiento regional",
    description: 'Un viaje por el tiempo para descubrir el poder de "LA LEYENDA".',
    brand: "logo-paty",
    altBrand: "Logo Paty",
    img: "home_posicionamiento_regional",
    altImg: "Campaña Paty, posicionamiento regional",
    subtitle: 'Paty, junto al famoso comediante chileno Rodrigo Salinas, te invita a un viaje por el tiempo para descubrir el poder de "LA LEYENDA".',
    objective: "Paty, una marca líder en Argentina, enfrentaba el desafío de lograr un reconocimiento similar en el mercado chileno. En 2016, la empresa decidió lanzar una campaña 360° para incrementar la pregnancia y el engagement de la marca en Chile, abordando así el problema de su baja visibilidad y posicionamiento en este mercado.",
    campain: ["Para alcanzar este nuevo posicionamiento en Chile, lanzamos una campaña protagonizada por el comediante y actor Rodrigo Salinas, una figura reconocida en el país. Su participación dio a Paty una comunicación fresca y divertida, manteniendo su espíritu de TRADICIÓN EN CARNES.", 'La campaña incluyó diferentes activaciones: Un gran evento en las playas de Viña del Mar, Reñaca y La Serena, donde los usuarios podían subirse a un toro mecánico con la forma del logo de Paty; y una serie de videos interactivos en los que las personas podían actuar y aparecer junto al comediante en un "viaje a través del tiempo".', "El lema de la campaña, ¡Anímate a domar tu hambre! #SubetealaLeyenda, invitaba al público a participar activamente y a conocer más sobre la marca."],
    results: {
      texts: ["La activación de Paty en la playa atrajo a más de 6.600 personas, y más de 4.900 recibieron su video subiéndose al toro e intentando DOMAR A LA LEYENDA. Estos videos fueron ampliamente compartidos en redes sociales, superando los 760.000 puntos de contacto potenciales.", "La campaña logró aumentar significativamente el nivel de awareness dentro del mercado chileno, alcanzando un récord de engagement en redes sociales y triplicando las ventas respecto al mismo período del año anterior."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "psicologo-del-color",
    title: "Psicólogo del color",
    description: "Sodimac convierte a uno de sus asesores en un psicólogo para ayudar a sus clientes a elegir el mejor color.",
    brand: "logo-sodimac",
    altBrand: "Logo Sodimac",
    img: "home_psicologo_del_color",
    altImg: "Campaña Psicólogo del color",
    subtitle: "En esta campaña, Sodimac convierte a uno de sus asesores en un psicólogo para ayudar a sus clientes a elegir el mejor color.",
    objective: "Sodimac cuenta con un sector especializado para pinturas, donde los clientes pueden recibir asesoramiento personalizado y un servicio de entintado completamente gratis. Sin embargo, el desafío era comunicar este servicio y resaltar los beneficios de contar con asesores especializados, para incrementar el conocimiento y uso del servicio. El objetivo planteado era claro: lanzar una campaña en redes sociales para destacar estos beneficios y atraer más clientes a los servicios de pintura de Sodimac.",
    campain: ["La psicología del color es una rama de la psicología que estudia cómo los colores influyen en el comportamiento y las emociones de las personas. Basándonos en esta premisa, desarrollamos una campaña que convertía a uno de los asesores de Sodimac en un psicólogo especializado en colores.", 'Decidimos lanzar una serie de videos humorísticos en los que este "psicólogo del color" ayudaba a los clientes a elegir el color perfecto para sus hogares, demostrando así el valor de la asesoría personalizada. La campaña buscaba comunicar este servicio de una forma original y relajada, utilizando insights con los que el público se pudiera identificar fácilmente.'],
    results: {
      texts: ["La campaña fue recibida con gran entusiasmo por los usuarios, generando un amplio alcance en redes sociales y aumentando significativamente el número de consultas al sector de pinturas en las diferentes tiendas Sodimac del país. Esta estrategia no solo incrementó la visibilidad del servicio, sino que también fortaleció la percepción de la marca como experta en soluciones de pintura personalizadas."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "el-secreto-del-sabor",
    title: "El secreto del sabor",
    description: "¿Cómo transformar una receta normal en una extraordinaria? Llegó el secreto del sabor.",
    brand: "logo-ajinomoto",
    altBrand: "Logo Ajinomoto",
    img: "home_el_secreto_del_sabor",
    altImg: "Campaña El secreto del sabor",
    subtitle: "¿Cómo puedo transformar una receta normal en una extraordinaria? Llegó el momento de revelar el secreto del sabor.",
    objective: "Ajinomoto, conocida por sus productos realzadores de sabor a base de glutamato monosódico, ha establecido su presencia en mercados como el peruano y el brasilero. Sin embargo, en Argentina la marca no tenía aún el mismo nivel de reconocimiento, y sus redes sociales estaban en etapas iniciales. El cliente nos pidió crear una campaña masiva para presentar su producto estrella, el realzador de sabor Aji-no-moto, y aumentar su notoriedad en el mercado argentino.",
    campain: ['Basándonos en la premisa "Todos los chefs del mundo esconden un gran secreto. El secreto para convertir un plato normal en uno inigualable. Y después de tanto tiempo llegó la hora de revelarlo", desarrollamos una campaña intrigante y cautivadora. Convocamos a Santiago Giorgini, un famoso cocinero de televisión, para desafiar a tres influencers de cocina con platos aparentemente idénticos. El desafío consistía en adivinar cuál de los platos contenía “EL SECRETO DEL SABOR”.', "Los videos de esta campaña, llenos de suspenso y revelación, buscaban captar la atención de los usuarios y dar a conocer Ajinomoto en el mercado argentino de una manera original y atractiva."],
    results: {
      texts: ["La campaña fue un gran éxito, logrando aumentar significativamente el número de seguidores de la marca en las redes sociales, generar un interés genuino por Ajinomoto y sus productos, incrementar las ventas en supermercados y crear una nueva línea de contenidos (video recetas) en colaboración con los influencers que participaron del desafío."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "devuelta-a-la-vida",
    title: "Devuelta a la vida",
    description: "Un documental que muestra al cáncer como algo más que una enfermedad… como un lugar de superación",
    brand: "logo-fuca",
    altBrand: "Logo FUCA",
    img: "home_devuelta_a_la_vida",
    altImg: "Campaña Devuelta a la vida",
    subtitle: "Un documental que muestra al cáncer como algo más que una enfermedad… como un lugar de superación.",
    objective: "unto con FUCA, decidimos llevar adelante uno de nuestros proyectos más ambiciosos: un documental que no solo informara sobre el cáncer de mama, sino que también reflejara la superación personal de quienes lo han enfrentado. El desafío era doble: crear una pieza que inspirara y concientizara, mientras se rendía homenaje a los sobrevivientes de la caída del avión de los uruguayos en 1972, 50 años atrás. El objetivo principal era resaltar la importancia de la detección temprana del cáncer a través de historias reales de supervivencia.",
    campain: ["Para este proyecto, convocamos a un grupo de pacientes que sobrevivieron al cáncer de mama para emprender un viaje al Valle de las Lágrimas en marzo de 2022, junto al Dr. Fernando Petracci y otros médicos del Instituto Alexander Fleming. Este viaje no solo fue una travesía física, sino también una intensa experiencia emocional que los invitó a reflexionar, recordar y rendir homenaje a los sobrevivientes del accidente aéreo.", "Para promocionar el lanzamiento de este emotivo e inspirador documental, creamos una campaña de cobranding con Starbucks Argentina. Esta acción tenía como objetivo seguir concientizando sobre la importancia de realizarse chequeos a tiempo, lanzando el nuevo Ultra Frutilla Creme Frappuccino. Con la compra de cada uno de estos frappuccinos, los clientes participaban en un sorteo para ganar entradas para ver el documental en el cine, y parte del dinero recaudado fue destinado al Instituto Alexander Fleming."],
    results: {
      texts: ['La campaña tuvo un impacto significativo, generando conciencia sobre la importancia de la detección temprana del cáncer de mama. El documental fue bien recibido, logrando una fuerte conexión emocional con la audiencia. La colaboración con Starbucks Argentina no solo aumentó la visibilidad del documental, sino que también incentivó a la comunidad a participar y contribuir a la causa, recaudando fondos importantes para el Instituto Alexander Fleming.'],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "evento-de-lanzamiento-nobili-vasser",
    title: "Evento de lanzamiento: Nobili + Vasser",
    description: "Nobili y Vasser unen calidad y sofisticación en un evento de lanzamiento inolvidable.",
    brand: "logo-vasser",
    altBrand: "Logo Vasser",
    img: "home_evento_lanzamiento_vasser",
    altImg: "Campaña Evento de lanzamiento: Nobili + Vasser",
    subtitle: "Un evento de sofisticación y diseño que presentó a Nobili y Vasser como referentes de calidad en Argentina.",
    objective: "Crear una experiencia memorable y auténtica que destaque la alianza entre la marca italiana Nobili, líder en griferías de alta gama en Europa, y Vasser, una reconocida marca nacional. El objetivo era posicionar a Nobili en el mercado argentino y fortalecer el compromiso de Vasser con la calidad y el diseño superior de sus productos.",
    campain: ['En este evento de lanzamiento, se desplegó un "halo de misterio" donde los asistentes descubrieron la llegada de Nobili a través de un spot promocional sorpresa. La campaña no solo buscó atraer a la audiencia a través de la intriga y la sorpresa, sino también fomentar la conexión y el engagement entre los participantes mediante actividades interactivas y dinámicas.', "El evento se llevó a cabo en el elegante Salón Faena, con la conducción de la reconocida Andrea Frigerio, lo que añadió un toque de sofisticación y exclusividad a la ocasión. Los invitados disfrutaron de una atmósfera refinada mientras descubrían la novedosa alianza entre Nobili y Vasser y los innovadores productos que llegaban al país.", "Desde nuestra agencia, nos encargamos integralmente de todo el proyecto, desde la concepción de las ideas creativas hasta la ejecución de cada instancia. Coordinamos cada detalle para asegurar que el evento reflejara la calidad y prestigio de ambas marcas."],
    results: {
      texts: ["El evento fue un éxito rotundo, logrando una excelente recepción por parte de los invitados y fortaleciendo la presencia de Nobili en Argentina. La alianza con Vasser se consolidó como un referente de calidad y diseño en el mercado. El evento y su toque sorpresa generaron un alto nivel de engagement y reconocimiento entre los participantes."],
      videos: ["", ""],
    },
    feature: true,
  },
  {
    slug: "klaukol-50-anos",
    title: "Klaukol 50 años",
    description: "Klaukol cumplió 50 años y decidió celebrarlo con todos: arquitectos, albañiles, vendedores, socios...",
    brand: "logo-klaukol",
    altBrand: "Logo Klaukol",
    img: "home_klaukol_cincuenta_anos",
    altImg: "Campaña Klaukol 50 años",
    subtitle: "Klaukol cumplió 50 años y decidió celebrarlo ¡CON TODO! y con todos: arquitectos, albañiles, vendedores, socios... todos están invitados.",
    objective: "Klaukol, marca líder en adhesivos cementicos (pegamento para cerámicos y porcelanatos) en Argentina, festejó su aniversario número 50. Y para celebrarlo nos propusieron llevar a cabo una campaña integral 360°, que se centrara en resaltar la trayectoria de la marca, así como también empoderar a su target profesional, por los años de confianza.",
    campain: ["Para homenajear a Klaukol con una campaña que estuviera a la altura de su trayectoria en Argentina, desarrollamos diferentes acciones, videos para redes sociales, sorteos e intervenciones en obras de construcción. Una campaña que nos invita a hacer un repaso por su historia, su misión como empresa, su compromiso y toda la gente que lo hizo posible."],
    results: {
      videos: ["", ""],
    },
    feature: true,
  },
  // NUEVOS
  {
    slug: "moto-wheel",
    title: "Moto Wheel",
    description: "Branding, Print Design",
    brand: "logo-brand3",
    altBrand: "Image",
    img: "works09",
    altImg: "Image",
    subtitle: "",
    objective: "",
    campain: ["", ""],
    results: {
      texts: ["", ""],
      videos: ["", ""],
    },
    awards: {
      texts: ["", ""],
      press: [
        {
          name: "",
          link: "",
        },
        {
          name: "",
          link: "",
        },
      ],
    },
  }
];
